INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"BIT",1,0,1,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"BOOL",1,0,1,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"TINYINT",3,0,3,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"TINYINT UNSIGNED",3,0,3,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"BIGINT",19,19,19,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"BIGINT UNSIGNED",20,20,20,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"LONG VARBINARY",16777215,0,16777215,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"MEDIUMBLOB",16777215,0,16777215,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"LONGBLOB",2147483647,0,2147483647,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"BLOB",65535,0,65535,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"TINYBLOB",255,0,255,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"VARBINARY(x)",255,20,255,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"BINARY(x)",255,20,255,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"LONG VARCHAR",16777215,0,16777215,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"MEDIUMTEXT",16777215,0,16777215,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"LONGTEXT",2147483647,0,2147483647,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"TEXT",65535,0,65535,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"TINYTEXT",255,0,255,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"CHAR(x)",255,20,255,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"NUMERIC",65,0,65,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"DECIMAL(x,y)",65,10,10,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"INTEGER(x)",10,10,10,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"INTEGER UNSIGNED(x)",10,10,10,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"INT",10,0,10,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"INT UNSIGNED",10,0,10,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"MEDIUMINT",7,0,7,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"MEDIUMINT UNSIGNED",8,0,8,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"SMALLINT",5,0,5,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"SMALLINT UNSIGNED",5,0,5,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"FLOAT(x,y)",10,0,10,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"DOUBLE(x,y)",17,0,17,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"DOUBLE PRECISION",17,0,17,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"REAL",17,0,17,true);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"VARCHAR(x)",255,20,255,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"ENUM(list)",65535,0,65535,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"SET(list)",64,0,64,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"DATE",0,0,0,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"TIME",0,0,0,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"DATETIME",0,0,0,false);
INSERT INTO database_architecture_data_type(database_architecture_code,data_type,max_width,default_size,max_width_of_precision,allow_auto_increment) VALUES(1,"TIMESTAMP",0,0,0,false);
