Insert into database_engine(database_architecture_code,name) values(1,"InnoDB");
Insert into database_engine(database_architecture_code,name) values(2,"InnoDB");
Insert into database_engine(database_architecture_code,name) values(4,"InnoDB");
Insert into database_engine(database_architecture_code,name) values(2,"sandbox");
Insert into database_engine(database_architecture_code,name) values(3,"sandbox");
Insert into database_engine(database_architecture_code,name) values(4,"sandbox");
Insert into database_engine(database_architecture_code,name) values(1,"merge");
Insert into database_engine(database_architecture_code,name) values(3,"merge");
Insert into database_engine(database_architecture_code,name) values(4,"merge");
